package event

// Generated by https://quicktype.io

// MESSAGE_CREATED / DIRECT_MESSAGE_CREATED イベントリクエストボディスキーマ
type MessageEvent struct {
	EventTime string  `json:"eventTime"`
	Message   Message `json:"message"`
}

// メッセージスキーマ
type Message struct {
	ID        string     `json:"id"`
	User      User       `json:"user"`
	ChannelID string     `json:"channelId"`
	Text      string     `json:"text"`
	PlainText string     `json:"plainText"`
	Embedded  []Embedded `json:"embedded"`
	CreatedAt string     `json:"createdAt"`
	UpdatedAt string     `json:"updatedAt"`
}

// 埋め込み要素スキーマ
type Embedded struct {
	Raw  string `json:"raw"`
	Type string `json:"type"`
	ID   string `json:"id"`
}

// ユーザースキーマ
type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	IconID      string `json:"iconId"`
	Bot         bool   `json:"bot"`
}

// メッセージテキスト 取得メソッド
func (body *MessageEvent) GetText() string {
	return body.Message.PlainText
}

// チャンネルID 取得メソッド
func (body *MessageEvent) GetChannelID() string {
	return body.Message.ChannelID
}

// ユーザーID 取得メソッド
func (body *MessageEvent) GetUserID() string {
	return body.Message.User.Name
}

// Embedded 配列取得メソッド
func (body *MessageEvent) GetEmbeddedList() []Embedded {
	return body.Message.Embedded
}
