package event

// Generated by https://quicktype.io

// JOINED / LEFT イベントリクエストボディスキーマ
type SystemEvent struct {
	EventTime string  `json:"eventTime,omitempty"`
	Channel   Channel `json:"channel,omitempty"`
}

// チャンネルスキーマ
type Channel struct {
	ID        string  `json:"id,omitempty"`
	Name      string  `json:"name,omitempty"`
	Path      string  `json:"path,omitempty"`
	ParentID  string  `json:"parentId,omitempty"`
	Creator   Creator `json:"creator,omitempty"`
	CreatedAt string  `json:"createdAt,omitempty"`
	UpdatedAt string  `json:"updatedAt,omitempty"`
}

// チャンネルクリエイタースキーマ
type Creator struct {
	ID          string `json:"id,omitempty"`
	Name        string `json:"name,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	IconID      string `json:"iconId,omitempty"`
	Bot         bool   `json:"bot,omitempty"`
}

// チャンネルID 取得メソッド
func (body *SystemEvent) GetChannelID() string {
	return body.Channel.ID
}

// チャンネルパス 取得メソッド
func (body *SystemEvent) GetChannelPath() string {
	return body.Channel.Path
}
