package api

import (
	"encoding/json"
	"fmt"
	"io"
)

// Generated by https://quicktype.io

type ChannelInfo struct {
	ID       string   `json:"id"`
	ParentID string   `json:"parentId"`
	Archived bool     `json:"archived"`
	Force    bool     `json:"force"`
	Topic    string   `json:"topic"`
	Name     string   `json:"name"`
	Children []string `json:"children"`
}

func (api *API) GetChannelNameByID(chanID string) (string, error) {
	// URL を生成
	url := fmt.Sprintf("%s/channels/%s", baseUrl, chanID)

	// リクエストを送信
	res, err := api.Get(url)
	if err != nil {
		return "", err
	}

	// ボディを読み込み、構造体にバインド
	defer res.Body.Close()
	body, err := io.ReadAll(res.Body)
	if err != nil {
		return "", err
	}

	bytes := []byte(body)
	var channelInfo ChannelInfo
	err = json.Unmarshal(bytes, &channelInfo)
	if err != nil {
		return "", err
	}

	return channelInfo.Name, nil
}
